### PR TITLE
Manually enable project explorer

### LINKED ISSUE #357: Disable Project Explorer (Tree)
@sebeder please fill out

### PR DESCRIPTION
**Pull request by sebeder**
Closes #357

### CODE REVIEW

**Review by wehrlean — DISMISSED** [review]
Works, but I would it merge with #358 because it is a bit confusing without project explorer and no search bar

**Comment by sebeder** [comment]
> Works, but I would it merge with #358 because it is a bit confusing without project explorer and no search bar

That's perfect. Then let's finish #358 and then merge this one, too.

**Comment by wehrlean** [comment]
The test fails (not the UI Test). Please check before merge

**Comment by sebeder** [comment]
> The test fails (not the UI Test). Please check before merge

That's a differents issue... `testGenerateTestsWithMutExConstraint` fails. I think, this was an issue by the relaxation of Liggesmeyer rules. I'll file another issue for @junkerm

**Comment by sebeder** [comment]
Hi @wehrlean , I just fixed merge conflicts and the other PR is done. Could you have another short look?

**Comment by sebeder** [comment]
Hi @wehrlean , sorry, now, that @junkerm is back, we can push this one further and enable project-dependent configuration of the project explorer.

**Review by wehrlean — APPROVED** [review]
Fine, you could merge it, although it is a bit strange without project explorer

**Pull request merged**
