### PR TITLE
Rework search semantics

### PR DESCRIPTION
**Pull request by sebeder**
[Trello Card](https://trello.com/c/UEQI3fkq/741-bestehende-anforderungen-und-tests-durchsuchen)
[Trello Card](https://trello.com/c/JN1IfdpR/740-prozessmodellverkn%C3%BCpfungssuche-zeigt-nicht-alle-ergebnisse-an)

### CODE REVIEW

**Review by wehrlean — CHANGES_REQUESTED** [review]
The following queries does not have the result I expected:

| Nr | Requirement(s) | SearchTerm | Expected Result | Real result
| - |-------------| -----| ---- |---|
| 1 | Title: _ID-1_; ID: _ID-1_ | ID-1 | only the requirement with this id | all requirements with prefix _ID-_ 
| 2 | Title: _-Text_; ID: _-Text_ | -Tex | only the requirement with this id | no result
| 3 | Title: _+Text_; ID: _+Text_ | +Tex | only the requirement with this id | no result
| 4 | Title: _Requirement_; ID: _Requirement_ | Req | the requirement with this id | no result

**Comment by sebeder** [comment]
Hi @wehrlean ,
I just changed the behavior again. Now, the search terms have leading and trailing *s. The problem is, that we cannot get Lucene to search for special chars like + or -. To me, it seems that Lucene just ignores it. Please retest and tell me whether it's fine, please.

**Review by wehrlean — CHANGES_REQUESTED** [review]
Now nr 4 works again, for nr 2 and 3 it is okay since you can search only for the text. 
For nr 1 we have the same problem as before, that the _ID-_ searchterm does not find anything. I think you last version was better, because more (wrong) results are better then no result.
And if you search exact for _ID-1_ no result is found.

**Comment by sebeder** [comment]
I changed the escaping again. And now, I think, we're fine.

**Review by wehrlean — APPROVED** [review]

**Pull request merged**
