### PR TITLE
Adding loading animations to updates and deletes

### PR DESCRIPTION
**Pull request by sebeder**
[Trello Card](https://trello.com/c/W1ISpmKf/733-lade-animation-be-l%C3%B6schen-aus-papierkorb)

### CODE REVIEW

**Comment by sebeder** [comment]
Hi @wehrlean , works now. I just had to fix several things to make it work.

**Review by wehrlean — CHANGES_REQUESTED** [review]
I think it does not work for the validation button. I takes a few seconds for big models, but no modal appears

**Comment by sebeder** [comment]
*grml* I thought I had this working. I'll have another look. Thanks! And I need to resolve the conflicts anyways.

**Comment by sebeder** [comment]
OK, I had another look. We have the issue, that the UI-thread blocks while validating (or something else after clicking the validate-button. I do not think it's actually an issue of the modal-mechanism, but the validator itself. I'd suggest to file another issue for that? @wehrlean , do you agree?

**Comment by wehrlean** [comment]
Yes its fine for me. You can merge it

**Pull request merged**
