### PR TITLE
Fix error messages

### PR DESCRIPTION
**Pull request by wehrlean**
[Trello Card](https://trello.com/c/HKbxcq1D/637-fehlermeldungen-sind-inkonsistent)

The following errors are changes/edited:

- Graphical Editor: Connecting two nodes twice shows now the normal Specmate error-dialog
- Model Generation: Changed text, if no model is created
- Model Generation: Errormessage, if something went wrong in backend
- Testspec generation: Edit error message, if model not valid
- Testspec generation: change _tools.addCegNode_ to variable and condition for new created ceg nodes

### CODE REVIEW

**Review by junkerm — CHANGES_REQUESTED** [review]
- The UI shows no error messages when generating a model from the *requirements view* and an error occurs, e.g. when you configure spacy as nlp engine and the url is wrong or if you just enter rubbish into the "Model Requirements" field (see screenshot)
grafik
- The error message in case of already connected nodes still looks very different from the other error mesages (e.g. when trying to generate a model)

**Comment by wehrlean** [comment]
First one is fixed
I think the second one already works, but it needs few rebuilds of the UI. I don't know why. It should look like the following
image

**Review by junkerm — APPROVED** [review]
Works! Could you investigate if the problem with the need to compile the UI several times persists? Otherwise we get problems with the build server. If this is ok please merge!

**Comment by wehrlean** [comment]
I do not know exactly either. Most of the time, building the UI once is enough. Sometimes you have to do it more often. I haven't discovered any regularity behind it. But I think it should work on the build server.

**Pull request merged**
