### PR TITLE
Accessibility increase font size

### LINKED ISSUE #327: Font size is too small
**Describe the bug**
The font size in Specmate is too small

**Expected behavior**
The font size shall be increased by at least 2 pixels

### PR DESCRIPTION
**Pull request by sebeder**
Closes #327

### CODE REVIEW

**Review by wehrlean — CHANGES_REQUESTED** [review]
I don't like it, but we have to do it. 
We had a size of 13.125px before. Now it is 17.5px. So I think the scale is a little bit to high.  I would use something like 1.15 or 1.20. (Btw. Jira has a fontsize of 14px).
The same is for the fontsize of the nodes. Maybe something like 15px or 16px.
Additional we have to scale the nodes:
image
Other problems:
image

**Comment by sebeder** [comment]
Thank you for the review! I adjusted the sizes accordingly.

**Review by wehrlean — DISMISSED** [review]
Looks better

**Comment by sebeder** [comment]
I just resolved the conflict and need another review.

**Review by wehrlean — APPROVED** [review]

**Pull request merged**
