### PR TITLE
Fix object comparisons

### PR DESCRIPTION
**Pull request by sebeder**
[Trello Card](https://trello.com/c/zRPknd5p/573-beim-verlassen-einer-testprozedur-wird-ein-warnfenster-angezeigt-obwohl-keine-%C3%A4nderungen-vorliegen)

### CODE REVIEW

**Review by wehrlean — CHANGES_REQUESTED** [review]
Works if a test procedure has been saved previously. 
If a completely new test procedure is created, the modal appears. This is not consistent with Specmate's normal behavior, as newly created items are normally saved automatically, e.g. new test specifications or new models are saved automatically.

**Comment by sebeder** [comment]
You're right. However, I'd consider this a new issue. Would that be fine for you?

**Comment by sebeder** [comment]
Actually, I could not reproduce the behavior you described. Can you explain this again to me?

**Comment by wehrlean** [comment]
A new issue would be ok for me.

Steps to reproduce:
1. Generate a new test specification (new test specification is saved automatically -> no modal if leaving)
2. Create new test procedure 
3. Leave the editor -> modal opens

I think the normal behavior would be, that no modals opens if nothing was changed.

**Review by wehrlean — APPROVED** [review]

**Pull request merged**
