### PR TITLE
Cookieless project change

### LINKED ISSUE #277: Cookie wird zu groß, wenn viele Jira Projekte existieren
**Describe the bug**
In der Testphase ist aufgefallen, dass wir (trotz vorhandener Lese- und Schreibrechte) nicht ordnungsgemäß auf die vom Multi Connector geladenen Jira Projekte zugreifen können. Der Connector ist in Prod somit aktuell nicht nutzbar.

**To Reproduce**
1. Click on a random Jira Project
2. Type in credentials
3. Login seems to work
4. However, after a few seconds you will be logged out again.

**Expected behavior**
Ich werde nicht ausgeloggt und kann mit der Modellierung anfangen.

**Additional context**
Das Problem besteht wohl in der Größe des Cookies (er wird größer als die maximale erlaubte Anzahl von 4096 Bytes). Wir müssen herausfinden, warum wir "so viel im Cookie" speichern und eine geeignete Lösung. Dieser Fehler ist definitiv geschäftskritisch und muss bis zum PROD deployment beseitigt werden.

@hauptmab: Sprech dich hier bitte mit @sebeder ab und klärt gemeinsam was man hier machen kann. Wir müssen das Verhalten dann wie gesagt noch auf DEV testen, das heißt die Deadline für die Bugreinigung ist der 05.03.21. Danke!

### LINKED ISSUE #281: Persistently store the selected project
**User Story**
As a user, I'd like to reload or close the specmate, but stay logged in, so that I can go home and continue working afterwards.

**Acceptance Criteria**
- The selected project is persistently stored on the users browser

### PR DESCRIPTION
**Pull request by sebeder**
Closes #281 
Closes #277

### CODE REVIEW

**Review by hauptmab — CHANGES_REQUESTED** [review]
I like this change a lot. I'm not too experienced with using `localStorage`, however, wouldn't using `sessionStorage` instead of `localStorage` allwoing to open open two different projects in different browser tabs/windows? This would be a nice feature.

**Comment by sebeder** [comment]
Good point. This would mean, that a user would have no valid project after closing the window - which would mean the user would be logged out after closing all Specmate-tabs. Is that desired, @fischJan ?

**Comment by hauptmab** [comment]
> which would mean the user would be logged out after closing all Specmate-tabs.

That is a good point as well.
A solution would be to store the last known project in the localStorage to handle (accidentelly) closing a window/tab. We could reuse this information then to try to *recover* an potentially open session.

However, it would make everyhing a litte bit more complex

**Comment by fischJan** [comment]
> Good point. This would mean, that a user would have no valid project after closing the window - which would mean the user would be logged out after closing all Specmate-tabs. Is that desired, @fischJan ?

In my opinion, this would be ok. We can assume that a user, who closes all (!) specmate tabs, wants to log out from his session. @hauptmab @sebeder

**Comment by sebeder** [comment]
- I tried using the sessionStorage, but this produced rather strange results. I think the lifecycle of the sessionStorage was not how I intuitively assumed it. I use the localStorage again.
- I removed the session cookie completely.
- I changed the project chooser to a typeahead-control

**Review by hauptmab — DISMISSED** [review]

**Comment by sebeder** [comment]
For me, the changes are fine. I still need an approving review to enable the merge.

**Review by hauptmab — APPROVED** [review]

**Pull request merged**
