### PR TITLE
cookies are set depending on http/https

### PR DESCRIPTION
**Pull request by hauptmab**
[Trello Card]()

### CODE REVIEW

**Comment by hauptmab** [comment]
In the UI-part, I had to add the same function twice. I might be a good idea to refactore that. However, I had no idea what would be a good place for that. Maybe a new angular component?
Hopefully, @sebeder has a good idea for that.

**Comment by sebeder** [comment]
I think the best solution would be an extra class like Cookie or CookieUtil that has a statix method that encapsulates the method.

**Review by sebeder — APPROVED** [review]
Looks absolutely fine to me! (I cannot test it, but I trust your thoroughness.) However, there seem to be formatting issues in `CookieService`, in line 12. I'll correct these and merge.

**Comment by sebeder** [comment]
I'll wait for the pipelines to finish. In case they run successfully, I'll merge.

**Pull request merged**
