### PR TITLE
Item search

### LINKED ISSUE #355: Extended Search
# Story

As a user, I want to filter work items efficiently and intuitively, so that I can find them quickly.

# Acceptance criteria:

- There is a panel for extended search
- The user can search by name
- The user can search by extId
- The user can search by description
- There is a preview of the search results (e.g., as typeahead)

### PR DESCRIPTION
**Pull request by sebeder**
Closes #355

### CODE REVIEW

**Review by wehrlean — CHANGES_REQUESTED** [review]
1. On my computer the  search for title and Description is not working, see screenshots:
2. it would be nice if the results are scrollable
3. If I rename a model, the search still search for the old name
image

image
Here it only worked for some descriptions eg : "_as a user..."

**Comment by sebeder** [comment]
I think that the non working search iscaused by a slowly updating lucene index. I cannot reproduce the behavior here. But I'll try it on the same project.

I am afraid we cannot make the results scrollable - this is something from an external controland thus would become a little hacky.

**Comment by wehrlean** [comment]
I made a reindex, so lucene should have all items. But maybe I was to fast.

Ok, the scrolling is not that important, you can skip it

**Comment by wehrlean** [comment]
Maybe we can disable the searchbar over the project explorer as well. I think two of them are a little bit confusing

**Comment by sebeder** [comment]
> Maybe we can disable the searchbar over the project explorer as well. I think two of them are a little bit confusing

Yeah definitely. I'll do that! Edit: I did that.

**Comment by sebeder** [comment]
> I made a reindex, so lucene should have all items. But maybe I was to fast.
> 
> Ok, the scrolling is not that important, you can skip it

I still cannot reproduce it. We should meet on that.

**Comment by sebeder** [comment]
Hi @wehrlean , I just talked to @fischJan and in his opinion, we can merge this also with the suboptimal search result performance. I'll open an issue with the search omitting stop words.

**Comment by sebeder** [comment]
See #363

**Review by wehrlean — APPROVED** [review]

**Pull request merged**
